---

- name: "skeleton | text block"
  blockinfile:
    block: |
      Explanation: Prefer GitLab provided packages over the Debian native ones
      Package: "{{ package_name }}"
      Pin: origin packages.gitlab.com
      Pin-Priority: 1001
    path: "/etc/apt/preferences.d/pin-gitlab-runner.pref"
    create: yes
    owner: root
    group: root
