---

- name: "skeleton | create directories"
  file:
    path: "{{ _directory }}"
    state: directory
    recurse: yes
    owner: root
    group: root
  loop:
    - "/var/lib/foo"
    - "/var/lib/foo/scripts"
  loop_control:
    loop_var: _directory
