---

- name: "skeleton | install skeleton requirements"
  include_tasks: "repo-{{ ansible_os_family | lower() }}.yml"
  tags:
    - "skeleton-repository"
    - "skeleton-install"

- name: "skeleton | configure skeleton"
  include_tasks: "configure.yml"
  tags:
    - "skeleton-configure"
    - "skeleton-install"
